name: Build and Deploy Docker Image

on:
  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      matrix:
        runner:
          - { on: self-hosted, for: linux/arm64 }
          - { on: ubuntu-latest, for: linux/amd64 }
        app:
          - { name: vem_questoes, dir: ./ }

    runs-on: ${{ matrix.runner.on }}

    steps:
    - name: Preset Image Name
      run: echo "IMAGE_URL=$(echo registry.apps.vadolasi.dev:996/captain-vem-questoes/$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: registry.apps.vadolasi.dev:996
        username: captain
        password: 7b7a4f9b-0031-40bc-8744-1d4fb1f19e38

    - name: Build and push Docker Image
      uses: docker/build-push-action@v4
      with:
        platforms: ${{ matrix.runner.for }}
        context: ${{ matrix.app.dir }}
        file: ${{ matrix.app.dir }}/Dockerfile
        push: true
        tags: ${{ env.IMAGE_URL }}

  deploy:
    needs: build

    runs-on: self-hosted

    steps:
    - name: Preset Image Name
      run: echo "IMAGE_URL=$(echo registry.apps.vadolasi.dev:996/captain-vem-questoes/$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Deploy Image to CapRrover
      uses: caprover/deploy-from-github@v1.1.2
      with:
        server: https://captain.apps.vadolasi.dev
        app: vem-questoes
        token: "4d2d6cc1710211ecde91db34e485e9f8261d5585690b21951537fb66782b9b70"
        image: ${{ env.IMAGE_URL }}
