name: Build and Deploy Docker Image

on:
  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      matrix:
        runner:
          - { on: self-hosted, for: linux/arm64 }
          - { on: ubuntu-latest, for: linux/amd64 }
        app:
          - { name: vem_questoes_frontend, dir: ./frontend }
          - { name: vem_questoes_backend, dir: ./backend }

    runs-on: ${{ matrix.runner.on }}

    steps:
    - name: Preset Image Name
      run: echo "IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ matrix.app.name }}:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}

    - name: Build and push Docker Image
      uses: docker/build-push-action@v4
      with:
        platforms: ${{ matrix.runner.for }}
        context: ${{ matrix.app.dir }}
        file: ${{ matrix.app.dir }}/Dockerfile
        push: true
        tags: ${{ env.IMAGE_URL }}

  deploy:
    needs: build

    strategy:
      matrix:
        app:
          - vem_questoes_frontend
          - vem_questoes_backend

    runs-on: self-hosted

    steps:
    - name: Preset Image Name
      run: echo "IMAGE_URL=$(echo ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}:$(echo ${{ github.sha }} | cut -c1-7) | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Preset app token
      run: echo "APP_TOKEN=$(echo APP_TOKEN_${{ matrix.app }})" >> $GITHUB_ENV

    - name: Deploy Image to CapRrover
      uses: caprover/deploy-from-github@v1.1.2
      with:
        server: "${{ secrets.CAPROVER_SERVER }}"
        app: "${{ matrix.app }}"
        token: "${{ secrets[env.APP_TOKEN] }}"
        image: ${{ env.IMAGE_URL }}
